spring.datasource.url=jdbc:postgresql://localhost:5432/devguardian
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=Dhanushan23
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

devguardian.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
devguardian.jwt.expiration-ms=86400000
devguardian.gemini.api-key=${GCP_API_KEY}